services:
  raycast-ai-proxy:
    restart: unless-stopped
    build: .
    # The proxy runs on port 3000 inside the container.
    # Change the host port if needed.
    # You need to set this port in Raycast settings.
    ports:
      - '11435:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # No volumes needed - models are fetched dynamically from LiteLLM
    # volumes:
    environment:
      # Environment variables are loaded from .env file
      # Copy .env.example to .env and update with your values
      - API_KEY=${API_KEY}
      - BASE_URL=${BASE_URL}
      - MODEL_REFRESH_INTERVAL=${MODEL_REFRESH_INTERVAL}
